#cloud-config

hostname: sdmfle-n1.sdmfle.io
ssh-authorized-keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+23n/uBDWSurf7l0v3E23MlahQkSPuv5gb67ilFBkvxChgS6m3NchJcM0xiDF5zUVrRuB2X6zoC2u9a6Sh4dNeQ9oj7oXCtUTgL2gtDrdSbafVhv66qoIlhJqeH8zhEbeIl+Fjfs9oEU/+GTMJaIfK9B2fQKI/RMk14/YSyuJS/+jeXzbIJ5GQIeQvXSw1tytwSJzxqEV8ZoGWrP6CgyJSU+WckK1lQJXouVCJo8ZGJbomzN+cXCRh1ZRB0dytyuodOvfbmVsRnQYWCHwnRpckcd2Z/u6HI+gHT/PeDW3ZJVLOuRw4MEXu04ZaSMZrRhlTOQKJPO5T3tWu7YfuCSX jdaniel@ch-prd095
coreos:
  units:
    - name: 00-ens192.network
      runtime: true
      content: |
        [Match]
        Name=ens192

        [Network]
        DNS=8.8.8.8
        Address=10.5.5.13/24
        Gateway=10.5.5.254
    - name: loopback-interface.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ip link set lo down
        ExecStart=/usr/bin/ip addr flush dev lo
        ExecStart=/usr/bin/ip link set lo up
    - name: etcd2.service
      command: start
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.15.0.0/16" }'
      command: start
    - name: docker.service
      command: start
  etcd2:
    name: sdmfle-n1-s0.sdmfle.io
    discovery: https://discovery.etcd.io/e2c6dcfa68cb739bd73d6d841c093277
    advertise-client-urls: http://10.5.5.13:2379,http://10.5.5.13:4001
    initial-advertise-peer-urls: http://10.5.5.13:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://10.5.5.13:2380
write_files:
  - path: "/etc/motd"
    permissions: "0644"
    owner: "root"
    content: |
      **************************************************************************
                                  NOTICE TO USERS
        This is a DePaul University affiliated server. Authorized users only!
        All uses of this system  may be intercepted, monitored, and inspected.
      **************************************************************************
  - path: "/etc/profile.d/ps1.sh"
    permissions: "0777"
    owner: "root"
    content: |
      export DATE=$(date +"%Y-%m-%dT%H:%M:%S%Z")
      export PS1="\n\[\e[1;30m\][$$:$PPID - \j:\!\[\e[1;30m\]]\[\e[0;36m\] \$(date +%Y-%m-%dT%H:%M:%S%Z) \[\e[1;30m\][\[\e[1;34m\]\u@\H\[\e[1;30m\]:\[\e[0;37m\]${SSH_TTY:-o} \[\e[0;32m\]+${SHLVL}\[\e[1;30m\]] \[\e[1;37m\]\w\[\e[0;37m\] \n\$ "